

from components import * #alles van de klasse importeren

kopkwhmeter = Appliance("kopkwhmeter_H"  , "appliance")
teller = Teller("Teller_H", "teller")
bord1 = Bord("Bord1_V", "bord")
bord1 = Bord("bord1_V", "bord")
dif300 = Differential("Diff300_V", "differential")
dif30 = Differential("Diff30_V", "differential")
dif100 = Differential("Diff100_V", "differential")
dif3 = Differential("Diff3_V", "differential")

zek3001 = CircuitBreaker("zek3001_V", "circuit_breaker")
zek3002 = CircuitBreaker("zek3002_V", "circuit_breaker")
zek1001 = CircuitBreaker("zek1001_V", "circuit_breaker")
zek3003 = CircuitBreaker("zek3003_V", "circuit_breaker")
zek3004verl = CircuitBreaker("zek3004verl_V", "circuit_breaker")
vaatwas301 = Appliance("vaatwas301_H", "appliance")
droogkast3002 = Appliance("droogkast3002_H"  , "appliance")
oven3002 = Appliance("oven3002_H", "appliance")
lamp3004 = Appliance("lamp3004_H", "appliance")
microoven3002 = Appliance("microoven3002_H", "appliance")
contaxop3004 = Contax("contaxop3004_H", "appliance")
contaxopcontax = Contax("contaxopcontax_H", "appliance")
domo = Domomodule("Domomodule_H", "domomodule")
verlH = Verlichting("Verlichting_H", "verlichting")
verlH2 = Verlichting("Verlichting2_H", "verlichting")
verlH3 = Verlichting("Verlichting3_H", "verlichting")
verlH4 = Verlichting("Verlichting4_H", "verlichting")
verlH5 = Verlichting("Verlichting5_H", "verlichting")
zonnepaneelopdif3= Appliance("zonnepaneelopdif3_H", "appliance")
faaropcontax = Verlichting("faaropcontax_H", "verlichting")
verlicht1 = Verlichting("Verlicht1_H", "verlichting")
verlicht2 = Verlichting("Verlicht2_H", "verlichting")
verlicht3 = Verlichting("Verlicht3_H", "verlichting")
tv = Appliance("tv_H", "appliance")
tv2 = Appliance("tv2_H", "appliance")
domo.add_child(verlH)
teller.add_child(dif300, dif30, dif3)
dif300.add_child(zek3001 , zek3002 , zek3003)
zek3001.add_child(droogkast3002  )
zek3002.add_child(oven3002 , microoven3002)
zek3003.add_child(tv , tv2 , domo  )
tv2.add_child( verlH2,   verlH3 , verlH4 , verlH5)
zek3004verl.add_child(verlicht1, verlicht2   , verlicht3 , lamp3004 )
zek3004verl.add_child(contaxop3004)
dif300.add_child(zek3004verl)
zek1001.add_child(vaatwas301)
dif300.add_child(dif100)
contaxop3004.add_child(contaxopcontax)
contaxopcontax.add_child(faaropcontax)
dif3.add_child(zonnepaneelopdif3)
dif100.add_child(zek1001)
kopkwhmeter.add_child(teller)

te_tekenen_startpunt = teller